name: Deploy Elevate Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH Deploy to OPC Server
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/github-actions
          chmod 600 ~/.ssh/github-actions
          ssh-keygen -lf ~/.ssh/github-actions

      - name: SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ~/.ssh/github-actions \
              -o IdentitiesOnly=yes \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/opc/Elevate-Backend
            git pull origin main
            npm install
            pm2 restart elevate-backend
          EOF