name: Deploy Elevate Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH Deploy to OPC Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/opc/Elevate-Backend
            git pull origin main
            npm install
            pm2 restart elevate-backend